// Explicit icon imports — guarantees these survive Next.js tree-shaking.
// Add any icon from lucide-react here and it will appear in the admin picker.
import type { ComponentType } from 'react'
import {
  // Photography & Media
  Camera, CameraOff, Aperture, Image, Film, Video, VideoOff, Eye, EyeOff,
  Scan, SlidersHorizontal, Focus, Maximize, Minimize, ZoomIn, ZoomOut,
  // Communication
  Mail, MailOpen, Phone, PhoneCall, MessageSquare, MessageCircle, Send,
  Inbox, Bell, BellOff, AtSign, Voicemail,
  // Social & Web
  Instagram, Twitter, Facebook, Youtube, Linkedin, Github,
  Globe, Rss, Share2, Link, ExternalLink, Wifi,
  // Location
  MapPin, Map, Navigation, Compass, Home, Building2, Building,
  // People
  User, Users, UserCheck, UserPlus, UserMinus, Contact,
  // Business & Work
  Briefcase, Calendar, Clock, AlarmClock, BarChart2, BarChart,
  TrendingUp, TrendingDown, Tag, Package, ShoppingBag, ShoppingCart,
  Monitor, Smartphone, Tablet, Printer, Cpu, Server,
  // Creative & Design
  Palette, Pen, PenTool, Brush, Scissors, Layers, LayoutDashboard,
  Grid2x2, Type, Bold, Italic, Underline, AlignLeft, AlignCenter, AlignRight,
  // Nature & Mood
  Sun, Moon, Cloud, CloudRain, Leaf, TreePine, Flower2,
  Sparkles, Flame, Snowflake, Wind, Droplets,
  // Ratings & Status
  Star, Heart, HeartHandshake, Award, Trophy, Medal, ThumbsUp, ThumbsDown,
  // Alerts & Info
  Check, CheckCircle, CheckCircle2, Circle, Info, AlertCircle, AlertTriangle,
  Shield, ShieldCheck, Lock, Unlock, Key, Zap,
  // Navigation
  ArrowRight, ArrowLeft, ArrowUp, ArrowDown, ArrowUpRight,
  ChevronRight, ChevronLeft, ChevronDown, ChevronUp,
  ChevronsRight, ChevronsLeft, MoveRight, CornerDownRight,
  // Actions & UI
  Search, Download, Upload, RefreshCw, RotateCcw, Settings, Settings2,
  Bookmark, BookmarkPlus, Flag, Share, Copy, Clipboard, Edit, Trash2,
  Plus, Minus, X, XCircle, MoreHorizontal, MoreVertical, Menu, Grip,
  // Misc & Lifestyle
  Quote, Music, Headphones, Mic, BookOpen, Book, Coffee, Gift,
  Lightbulb, Rocket, Target, Fingerprint, Smile, Laugh, Meh, Frown,
  Newspaper, FileText, Folder, FolderOpen, Archive, Inbox as InboxIcon,
} from 'lucide-react'

export type IconComponent = ComponentType<{ size?: number; color?: string; strokeWidth?: number }>

export const ICON_MAP: Record<string, IconComponent> = {
  // Photography & Media
  camera: Camera,
  'camera-off': CameraOff,
  aperture: Aperture,
  image: Image,
  film: Film,
  video: Video,
  'video-off': VideoOff,
  eye: Eye,
  'eye-off': EyeOff,
  scan: Scan,
  'sliders-horizontal': SlidersHorizontal,
  focus: Focus,
  maximize: Maximize,
  minimize: Minimize,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  // Communication
  mail: Mail,
  'mail-open': MailOpen,
  phone: Phone,
  'phone-call': PhoneCall,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  send: Send,
  inbox: InboxIcon,
  bell: Bell,
  'bell-off': BellOff,
  'at-sign': AtSign,
  voicemail: Voicemail,
  // Social & Web
  instagram: Instagram,
  twitter: Twitter,
  facebook: Facebook,
  youtube: Youtube,
  linkedin: Linkedin,
  github: Github,
  globe: Globe,
  rss: Rss,
  'share-2': Share2,
  link: Link,
  'external-link': ExternalLink,
  wifi: Wifi,
  // Location
  'map-pin': MapPin,
  map: Map,
  navigation: Navigation,
  compass: Compass,
  home: Home,
  'building-2': Building2,
  building: Building,
  // People
  user: User,
  users: Users,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  contact: Contact,
  // Business & Work
  briefcase: Briefcase,
  calendar: Calendar,
  clock: Clock,
  'alarm-clock': AlarmClock,
  'bar-chart-2': BarChart2,
  'bar-chart': BarChart,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  tag: Tag,
  package: Package,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  printer: Printer,
  cpu: Cpu,
  server: Server,
  // Creative & Design
  palette: Palette,
  pen: Pen,
  'pen-tool': PenTool,
  brush: Brush,
  scissors: Scissors,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  'grid-2x2': Grid2x2,
  type: Type,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  // Nature & Mood
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  leaf: Leaf,
  'tree-pine': TreePine,
  'flower-2': Flower2,
  sparkles: Sparkles,
  flame: Flame,
  snowflake: Snowflake,
  wind: Wind,
  droplets: Droplets,
  // Ratings & Status
  star: Star,
  heart: Heart,
  'heart-handshake': HeartHandshake,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  // Alerts & Info
  check: Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  circle: Circle,
  info: Info,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  shield: Shield,
  'shield-check': ShieldCheck,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  zap: Zap,
  // Navigation arrows
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-up-right': ArrowUpRight,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevrons-right': ChevronsRight,
  'chevrons-left': ChevronsLeft,
  'move-right': MoveRight,
  'corner-down-right': CornerDownRight,
  // Actions & UI
  search: Search,
  download: Download,
  upload: Upload,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  settings: Settings,
  'settings-2': Settings2,
  bookmark: Bookmark,
  'bookmark-plus': BookmarkPlus,
  flag: Flag,
  share: Share,
  copy: Copy,
  clipboard: Clipboard,
  edit: Edit,
  'trash-2': Trash2,
  plus: Plus,
  minus: Minus,
  x: X,
  'x-circle': XCircle,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  menu: Menu,
  grip: Grip,
  // Misc & Lifestyle
  quote: Quote,
  music: Music,
  headphones: Headphones,
  mic: Mic,
  'book-open': BookOpen,
  book: Book,
  coffee: Coffee,
  gift: Gift,
  lightbulb: Lightbulb,
  rocket: Rocket,
  target: Target,
  fingerprint: Fingerprint,
  smile: Smile,
  laugh: Laugh,
  meh: Meh,
  frown: Frown,
  newspaper: Newspaper,
  'file-text': FileText,
  folder: Folder,
  'folder-open': FolderOpen,
  archive: Archive,
}

export const ICON_NAMES = Object.keys(ICON_MAP).sort()
