/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * The URL path, e.g. "publish-story" → /publish-story. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  layout?:
    | (
        | BannerBlock
        | HeadingBlock
        | TextBlock
        | ImageBlock
        | GalleryBlock
        | IconBoxBlock
        | ButtonBlock
        | ColumnsBlock
        | RowBlock
        | MarginBlock
        | FormBlockType
      )[]
    | null;
  /**
   * Show the page title as an H1 at the top of the content.
   */
  showTitle?: boolean | null;
  /**
   * Uncheck to hide this page from the live site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  type?: ('fixed' | 'slideshow') | null;
  images: (number | Media)[];
  height?: ('small' | 'medium' | 'large' | 'full' | 'custom') | null;
  customHeight?: number | null;
  width?: ('full' | 'contained' | 'custom') | null;
  customWidth?: number | null;
  objectFit?: ('cover' | 'contain') | null;
  /**
   * How long each image is displayed before moving to the next.
   */
  slideDuration?: number | null;
  transition?: ('fade' | 'slide') | null;
  showDots?: boolean | null;
  showArrows?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  cloudinaryPublicId?: string | null;
  /**
   * Short description for accessibility and SEO.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlock".
 */
export interface HeadingBlock {
  text: string;
  level?: ('h2' | 'h3' | 'h4') | null;
  align?: ('left' | 'center') | null;
  linkType?: ('none' | 'page' | 'external') | null;
  linkPage?: (number | null) | Page;
  linkUrl?: string | null;
  linkNewTab?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  align?: ('left' | 'center') | null;
  width?: ('full' | 'readable') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: number | Media;
  caption?: string | null;
  width?: ('full' | 'large' | 'medium' | 'custom') | null;
  /**
   * Width in pixels
   */
  customWidth?: number | null;
  /**
   * Leave empty for natural image height
   */
  customHeight?: number | null;
  align?: ('left' | 'center' | 'right') | null;
  linkType?: ('none' | 'page' | 'external') | null;
  linkPage?: (number | null) | Page;
  linkUrl?: string | null;
  linkNewTab?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  images: (number | Media)[];
  columns?: ('2' | '3' | '4') | null;
  gap?: ('small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconBoxBlock".
 */
export interface IconBoxBlock {
  icon?: string | null;
  /**
   * Default is 28px.
   */
  iconSize?: number | null;
  /**
   * Hex colour e.g. #a8553a. Leave blank to use the accent colour.
   */
  iconColor?: string | null;
  heading?: string | null;
  description?: string | null;
  align?: ('left' | 'center') | null;
  linkType?: ('none' | 'page' | 'external') | null;
  linkPage?: (number | null) | Page;
  linkUrl?: string | null;
  linkNewTab?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconBox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock".
 */
export interface ButtonBlock {
  label: string;
  linkType?: ('page' | 'external') | null;
  page?: (number | null) | Page;
  url?: string | null;
  style?: ('outline' | 'solid') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnsBlock".
 */
export interface ColumnsBlock {
  columns?:
    | {
        blocks?: (HeadingBlock | TextBlock | ImageBlock | IconBoxBlock | ButtonBlock | MarginBlock)[] | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'columns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarginBlock".
 */
export interface MarginBlock {
  top?: number | null;
  right?: number | null;
  bottom?: number | null;
  left?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'margin';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RowBlock".
 */
export interface RowBlock {
  gap?: ('none' | 'small' | 'medium' | 'large') | null;
  verticalAlign?: ('top' | 'center' | 'bottom' | 'stretch') | null;
  stackOnMobile?: boolean | null;
  columns?:
    | {
        width?: ('auto' | '16' | '25' | '33' | '41' | '50' | '58' | '66' | '75' | '83' | '100') | null;
        blocks?:
          | (HeadingBlock | TextBlock | ImageBlock | GalleryBlock | IconBoxBlock | ButtonBlock | MarginBlock)[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'row';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlockType".
 */
export interface FormBlockType {
  form: number | Form;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        banner?: T | BannerBlockSelect<T>;
        heading?: T | HeadingBlockSelect<T>;
        text?: T | TextBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        iconBox?: T | IconBoxBlockSelect<T>;
        button?: T | ButtonBlockSelect<T>;
        columns?: T | ColumnsBlockSelect<T>;
        row?: T | RowBlockSelect<T>;
        margin?: T | MarginBlockSelect<T>;
        formBlock?: T | FormBlockTypeSelect<T>;
      };
  showTitle?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  type?: T;
  images?: T;
  height?: T;
  customHeight?: T;
  width?: T;
  customWidth?: T;
  objectFit?: T;
  slideDuration?: T;
  transition?: T;
  showDots?: T;
  showArrows?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlock_select".
 */
export interface HeadingBlockSelect<T extends boolean = true> {
  text?: T;
  level?: T;
  align?: T;
  linkType?: T;
  linkPage?: T;
  linkUrl?: T;
  linkNewTab?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  content?: T;
  align?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  width?: T;
  customWidth?: T;
  customHeight?: T;
  align?: T;
  linkType?: T;
  linkPage?: T;
  linkUrl?: T;
  linkNewTab?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  images?: T;
  columns?: T;
  gap?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconBoxBlock_select".
 */
export interface IconBoxBlockSelect<T extends boolean = true> {
  icon?: T;
  iconSize?: T;
  iconColor?: T;
  heading?: T;
  description?: T;
  align?: T;
  linkType?: T;
  linkPage?: T;
  linkUrl?: T;
  linkNewTab?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock_select".
 */
export interface ButtonBlockSelect<T extends boolean = true> {
  label?: T;
  linkType?: T;
  page?: T;
  url?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnsBlock_select".
 */
export interface ColumnsBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        blocks?:
          | T
          | {
              heading?: T | HeadingBlockSelect<T>;
              text?: T | TextBlockSelect<T>;
              image?: T | ImageBlockSelect<T>;
              iconBox?: T | IconBoxBlockSelect<T>;
              button?: T | ButtonBlockSelect<T>;
              margin?: T | MarginBlockSelect<T>;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarginBlock_select".
 */
export interface MarginBlockSelect<T extends boolean = true> {
  top?: T;
  right?: T;
  bottom?: T;
  left?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RowBlock_select".
 */
export interface RowBlockSelect<T extends boolean = true> {
  gap?: T;
  verticalAlign?: T;
  stackOnMobile?: T;
  columns?:
    | T
    | {
        width?: T;
        blocks?:
          | T
          | {
              heading?: T | HeadingBlockSelect<T>;
              text?: T | TextBlockSelect<T>;
              image?: T | ImageBlockSelect<T>;
              gallery?: T | GalleryBlockSelect<T>;
              iconBox?: T | IconBoxBlockSelect<T>;
              button?: T | ButtonBlockSelect<T>;
              margin?: T | MarginBlockSelect<T>;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlockType_select".
 */
export interface FormBlockTypeSelect<T extends boolean = true> {
  form?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  cloudinaryPublicId?: T;
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Build the left-hand menu. Drag rows to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        type?: ('page' | 'external' | 'dropdown') | null;
        page?: (number | null) | Page;
        url?: string | null;
        children?:
          | {
              label: string;
              type?: ('page' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Displayed in the sidebar and used as the default browser tab title.
   */
  siteTitle?: string | null;
  tagline?: string | null;
  /**
   * Browser tab icon. Use a square PNG or SVG, ideally 64×64 px or larger.
   */
  favicon?: (number | null) | Media;
  /**
   * The page shown when visitors hit the root URL (/).
   */
  homePage?: (number | null) | Page;
  /**
   * Overrides Site Title in the browser tab and search results. Leave blank to use Site Title.
   */
  metaTitle?: string | null;
  /**
   * Default description shown in search engine results.
   */
  metaDescription?: string | null;
  /**
   * Switch the whole site look. Applied instantly.
   */
  theme?: ('light' | 'warm' | 'dark') | null;
  /**
   * Optional. Overrides the theme colour for the sidebar.
   */
  sidebarBg?: string | null;
  /**
   * Optional. Overrides the theme colour for the content area.
   */
  pageBg?: string | null;
  /**
   * Thickness of the line between each menu item.
   */
  menuDividerHeight?: number | null;
  /**
   * Leave blank to use the theme line colour.
   */
  menuDividerColor?: string | null;
  /**
   * Used for the site name, page titles and headings.
   */
  headingFont?:
    | (
        | 'default'
        | 'Playfair Display'
        | 'Cormorant Garamond'
        | 'Lora'
        | 'Merriweather'
        | 'EB Garamond'
        | 'Libre Baskerville'
        | 'Fraunces'
        | 'Inter'
        | 'Poppins'
        | 'Montserrat'
        | 'Work Sans'
        | 'DM Sans'
        | 'Roboto'
        | 'Oswald'
        | 'custom'
      )
    | null;
  /**
   * Exact Google Fonts family name, e.g. "Playfair Display".
   */
  headingFontCustom?: string | null;
  /**
   * Used for body text and most of the interface.
   */
  bodyFont?:
    | (
        | 'default'
        | 'Playfair Display'
        | 'Cormorant Garamond'
        | 'Lora'
        | 'Merriweather'
        | 'EB Garamond'
        | 'Libre Baskerville'
        | 'Fraunces'
        | 'Inter'
        | 'Poppins'
        | 'Montserrat'
        | 'Work Sans'
        | 'DM Sans'
        | 'Roboto'
        | 'Oswald'
        | 'custom'
      )
    | null;
  /**
   * Exact Google Fonts family name, e.g. "Inter".
   */
  bodyFontCustom?: string | null;
  socials?:
    | {
        platform: 'instagram' | 'facebook' | 'x' | 'linkedin' | 'youtube' | 'github' | 'mail' | 'phone' | 'globe';
        /**
         * Full URL including https:// e.g. https://www.instagram.com/yourhandle — or mailto:you@example.com for email.
         */
        url: string;
        /**
         * Leave blank to use the platform icon.
         */
        icon?: string | null;
        /**
         * Optional hex colour e.g. #E1306C. Leave blank to inherit.
         */
        color?: string | null;
        /**
         * Default is 18 px.
         */
        size?: number | null;
        id?: string | null;
      }[]
    | null;
  copyrightLine1?: string | null;
  copyrightLine2?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  tagline?: T;
  favicon?: T;
  homePage?: T;
  metaTitle?: T;
  metaDescription?: T;
  theme?: T;
  sidebarBg?: T;
  pageBg?: T;
  menuDividerHeight?: T;
  menuDividerColor?: T;
  headingFont?: T;
  headingFontCustom?: T;
  bodyFont?: T;
  bodyFontCustom?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        color?: T;
        size?: T;
        id?: T;
      };
  copyrightLine1?: T;
  copyrightLine2?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}